INSERT INTO SKU_ITEM VALUES ('A', 50);
INSERT INTO SKU_ITEM VALUES ('B', 30);
INSERT INTO SKU_ITEM VALUES ('C', 20);
INSERT INTO SKU_ITEM VALUES ('D', 15);

INSERT INTO PROMOTION VALUES ('A', FALSE, 3, 130);
INSERT INTO PROMOTION VALUES ('B', FALSE, 2, 45);
INSERT INTO PROMOTION VALUES ('C&D', TRUE, 1, 30);