DROP TABLE IF EXISTS SKU_ITEM;
DROP TABLE IF EXISTS PROMOTION;
CREATE TABLE SKU_ITEM (ID VARCHAR PRIMARY KEY,
                      PRICE DECIMAL NOT NULL);
CREATE TABLE PROMOTION (ID VARCHAR PRIMARY KEY,
                      MULTI_ITEM_PROMOTION BOOLEAN NOT NULL,
                      QUANTITY INT NOT NULL,
                      PROMOTIONAL_ITEM_PRICE DECIMAL NOT NULL);